language: python
python:
- '3.6'
cache: pip
install:
- pip install --upgrade pip setuptools wheel
- pip install -e .
- pip install coveralls flake8
- pip install -r requirements.txt
script:
- flake8 .